#-- Lattice Semiconductor Corporation Ltd.
#-- Map run script generated by Radiant

set ret 0
if {[catch {

if {![file exists {C:/Users/billzhang/Desktop/I3C_XO5/I3C_XO5/impl_1}]} {
  file mkdir {C:/Users/billzhang/Desktop/I3C_XO5/I3C_XO5/impl_1}
}
cd {C:/Users/billzhang/Desktop/I3C_XO5/I3C_XO5/impl_1}

sys_set_attribute -gui on -msg {C:/Users/billzhang/Desktop/I3C_XO5/I3C_XO5/promote.xml}
msg_load {C:/Users/billzhang/Desktop/I3C_XO5/I3C_XO5/promote.xml}
des_set_project_udb -in {I3C_XO5_impl_1_syn.udb} -out {I3C_XO5_impl_1_map.udb} -milestone map -pm jd5f00
des_set_reference_udb -clean
map_set_option {pdc_file "C:/Users/billzhang/Desktop/I3C_XO5/I3C_XO5/source/impl_1/I3C_XO5.pdc"}
# map option
map_set_option { report_symbol_cross_reference false report_signal_cross_reference false infer_gsr false  ignore_constraint_errors false vio false}
map_run

} out]} {
   puts $out
   set ret 1
}
exit -force ${ret}
