//=============================================================================
// Verilog module generated by IPExpress    03/13/2026    09:57:19         
// Filename: i3c_xo5_la0_inst.v                                          
// Copyright(c) 2006 Lattice Semiconductor Corporation. All rights reserved.   
//=============================================================================

/* WARNING - Changes to this file should be performed by re-running IPexpress
or modifying the .LPC file and regenerating the core.  Other changes may lead
to inconsistent simulation and/or implemenation results */

i3c_xo5_la0 (
    .clk		(clk),
    .reset_n		(reset_n),
    .jtck		(jtck),
    .jrstn		(jrstn),
    .jce2		(jce2),
    .jtdi		(jtdi),
    .er2_tdo		(er2_tdo),
    .jshift		(jshift),
    .jupdate		(jupdate),
    .trigger_din_0	(trigger_din_0),
    .trigger_din_1	(trigger_din_1),
    .trigger_din_2	(trigger_din_2),
    .trigger_din_3	(trigger_din_3),
    .trigger_din_4	(trigger_din_4),
    .trigger_din_5	(trigger_din_5),
    .trigger_din_6	(trigger_din_6),
    .trigger_din_7	(trigger_din_7),
    .trigger_din_8	(trigger_din_8),
    .trigger_din_9	(trigger_din_9),
    .trace_din		(trace_din),
    .ip_enable    	(ip_enable)
)

object /* synthesis GSR=DISABLED */
object /* synthesis UGROUP=”i3c_xo5_la0_core” */
pragma // attribute UGROUP ”i3c_xo5_la0_core” 
;

