// >>>>>>>>>>>>>>>>>>>>>>> COPYRIGHT NOTICE <<<<<<<<<<<<<<<<<<<<<<<<<
// ------------------------------------------------------------------
// Copyright (c) 2019-2023 by Lattice Semiconductor Corporation
// ALL RIGHTS RESERVED
// ------------------------------------------------------------------
//
// IMPORTANT: THIS FILE IS USED BY OR GENERATED BY the LATTICE PROPEL™
// DEVELOPMENT SUITE, WHICH INCLUDES PROPEL BUILDER AND PROPEL SDK.
//
// Lattice grants permission to use this code pursuant to the
// terms of the Lattice Propel License Agreement.
//
// DISCLAIMER:
//
//  LATTICE MAKES NO WARRANTIES ON THIS FILE OR ITS CONTENTS, WHETHER
//  EXPRESSED, IMPLIED, STATUTORY, OR IN ANY PROVISION OF THE LATTICE
//  PROPEL LICENSE AGREEMENT OR COMMUNICATION WITH LICENSEE, AND LATTICE
//  SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTY OF MERCHANTABILITY OR
//  FITNESS FOR A PARTICULAR PURPOSE.  LATTICE DOES NOT WARRANT THAT THE
//  FUNCTIONS CONTAINED HEREIN WILL MEET LICENSEE'S REQUIREMENTS, OR THAT
//  LICENSEE'S OPERATION OF ANY DEVICE, SOFTWARE OR SYSTEM USING THIS FILE
//  OR ITS CONTENTS WILL BE UNINTERRUPTED OR ERROR FREE, OR THAT DEFECTS
//  HEREIN WILL BE CORRECTED.  LICENSEE ASSUMES RESPONSIBILITY FOR
//  SELECTION OF MATERIALS TO ACHIEVE ITS INTENDED RESULTS, AND FOR THE
//  PROPER INSTALLATION, USE, AND RESULTS OBTAINED THEREFROM.  LICENSEE
//  ASSUMES THE ENTIRE RISK OF THE FILE AND ITS CONTENTS PROVING DEFECTIVE
//  OR FAILING TO PERFORM PROPERLY AND IN SUCH EVENT, LICENSEE SHALL
//  ASSUME THE ENTIRE COST AND RISK OF ANY REPAIR, SERVICE, CORRECTION, OR
//  ANY OTHER LIABILITIES OR DAMAGES CAUSED BY OR ASSOCIATED WITH THE
//  SOFTWARE.  IN NO EVENT SHALL LATTICE BE LIABLE TO ANY PARTY FOR DIRECT,
//  INDIRECT,SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST
//  PROFITS, ARISING OUT OF THE USE OF THIS FILE OR ITS CONTENTS, EVEN IF
//  LATTICE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. LATTICE'S
//  SOLE LIABILITY, AND LICENSEE'S SOLE REMEDY, IS SET FORTH ABOVE.
//  LATTICE DOES NOT WARRANT OR REPRESENT THAT THIS FILE, ITS CONTENTS OR
//  USE THEREOF DOES NOT INFRINGE ON THIRD PARTIES' INTELLECTUAL PROPERTY
//  RIGHTS, INCLUDING ANY PATENT. IT IS THE USER'S RESPONSIBILITY TO VERIFY
//  THE USER SOFTWARE DESIGN FOR CONSISTENCY AND FUNCTIONALITY THROUGH THE
//  USE OF FORMAL SOFTWARE VALIDATION METHODS.
// ------------------------------------------------------------------

#include "i3c_controller.h"
#include "uart.h"
#include "utils.h"
#include <stdio.h>

#define I3C_SLAVE_NUMS 1
#define DATA_LENGTH 32
#define SLAVE_ADDR 0x20
#define STATIC_ADDR 0x0B
#define STATIC_ADDR_WR 0x16
#define STATIC_ADDR_RD 0x17

struct uart_instance uart_core_uart;
struct i3c_master_instance i3cm;
struct i3c_dev_info i3c_devinfo;

const uint8_t wr_buf[DATA_LENGTH] = {0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F,
                   0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1A, 0x1B, 0x1C, 0x1D, 0x1E, 0x1F};
uint8_t rd_buf[DATA_LENGTH];

static int lscc_uart_putc(char c, FILE *file)
{
	int ret = EOF;
	ret = uart_putc(&uart_core_uart, c);
	if (c == '\n' && ret == 0)
		ret = uart_putc(&uart_core_uart, '\r');
	return ret;
}

static int lscc_uart_getc(FILE *file)
{
	(void) file;
	return EOF;
}

static int lscc_uart_flush(FILE *file)
{
	(void) file;
	return 0;
}

int main(void) {
  uint8_t ret = 0;
  int i;
  uint8_t dyn_address;
  unsigned char *reg_value;

  i3c_devinfo.pid = 0;

  uart_init(&uart_core_uart, UART0_INST_BASE_ADDR, UART0_INST_SYS_CLK, UART0_INST_BAUD_RATE, 1, 8);

  if (i3c_master_init(&i3cm, I3C_M_INST_BASE_ADDR, 0, I3C_M_INST_GUI_I2C_SCL_PULSE_WIDTH-1, I3C_SLAVE_NUMS) == 0)
  {
    printf("I3C master initialization is success\n");
  } else {
    printf("Fail to initialize I3C master\n");
    return -1;
  }

  printf("STARTING DAA TEST...\n");

  ret = i3c_master_daa(&i3cm, &i3c_devinfo, &dyn_address, I3C_SLAVE_NUMS, SLAVE_ADDR);

  if (ret) {
    printf("Fail I3C master DAA: error = %d\n", ret);
  } else {
    printf("I3C master DAA is success\n");
#ifdef ENABLE_DAA_UID
    printf("bcr = %x\n", i3c_devinfo.bcr);
    printf("dcr = %x\n", i3c_devinfo.dcr);
    printf("pid = %016llx \n", i3c_devinfo.pid);
    printf("dyn addr = %x\n", i3c_devinfo.init_dyn_addr);
#endif
  }

//  printf("STARTING I3C TESTS: Private Read from Empty FIFO ...\n");
//  i3c_master_private_i3c_read(&i3cm, (uint8_t *) rd_buf, 2, SLAVE_ADDR);
//  printf("Read back data from I3C target (FIFO empty): %x\n", rd_buf[0]);
//  printf("Read back data from I3C target: %x\n", rd_buf[1]);

  printf("STARTING I3C TESTS: Private Write ...\n");
  printf("Writing data from I3C controller to the target\n");
  i3c_master_private_i3c_write(&i3cm, (uint8_t *) wr_buf, DATA_LENGTH, SLAVE_ADDR);

  printf("STARTING I3C TESTS: Private Read ...\n");
  i3c_master_private_i3c_read(&i3cm, (uint8_t *) rd_buf, DATA_LENGTH-2, SLAVE_ADDR);
  for (i = 0; i < DATA_LENGTH-2; i++)
  {
    printf("Read back data from I3C slave at count %d: %x\n", i, rd_buf[i]);

    if (rd_buf[i] == wr_buf[i]) {
      printf("Read data matches write\n");
    } else {
      printf("Data mismatch %x != %x\n", rd_buf[i], wr_buf[i]);
    }
  }

  i3c_master_private_i3c_read(&i3cm, (uint8_t *) rd_buf, 2, SLAVE_ADDR);
  printf("Read back data from I3C target: %x\n", rd_buf[0]);
  printf("Read back data from I3C target: %x\n", rd_buf[1]);

//  printf("STARTING I3C TESTS: Directed CCC ...\n");

//  printf("STARTING I2C TESTS...\n");

//  i3c_master_private_i2c_write(&i3cm, (uint8_t *) wr_buf, DATA_LENGTH, STATIC_ADDR_WR);
//  printf("Done I2C Write\n");

//  i3c_master_private_i2c_read(&i3cm, (uint8_t *) rd_buf, DATA_LENGTH, SLAVE_ADDR);
//  for (i = 0; i < DATA_LENGTH; i++)
//  {
//    printf("Read back data from I3C slave at count %d: %x\n", i, rd_buf[i]);

//    if (rd_buf[i] == wr_buf[i]) {
//      printf("Read data matches write\n");
//    } else {
//      printf("Data mismatch %x != %x\n", rd_buf[i], wr_buf[i]);
//    }
//  }


  printf("TEST FINISHED\n");

  return 0;
}

