onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/clk_i
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/rst_n_i
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/src_clk_scl_i
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/scl_io
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/sda_io
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/tx_valid_i
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/tx_data_i
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/tx_ready_o
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/rx_ready_i
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/rx_valid_o
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/rx_data_o
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/lmmi_request_i
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/lmmi_offset_i
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/lmmi_wr_rdn_i
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/lmmi_wdata_i
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/lmmi_ready_o
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/lmmi_rdata_valid_o
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/lmmi_rdata_o
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/lmmi_error_o
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/apb_psel_i
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/apb_penable_i
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/apb_paddr_i
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/apb_pwrite_i
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/apb_pwdata_i
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/apb_pready_o
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/apb_prdata_o
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/apb_pslverr_o
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/ahbl_hsel_i
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/ahbl_hready_i
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/ahbl_haddr_i
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/ahbl_hburst_i
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/ahbl_hsize_i
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/ahbl_hmastlock_i
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/ahbl_hprot_i
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/ahbl_htrans_i
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/ahbl_hwrite_i
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/ahbl_hwdata_i
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/ahbl_hreadyout_o
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/ahbl_hresp_o
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/ahbl_hrdata_o
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/int_o
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/sc_rst_o
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/ext_io_scl_i
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/ext_io_sda_i
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/ext_io_scl_oe
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/ext_io_sda_oe
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/ext_io_scl_o
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/ext_io_sda_o
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/ext_io_sda_spu_n
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/ext_io_scl_spu_n
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/ext_io_sda_wpu_n
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/ext_io_scl_wpu_n
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/lmmi_error_i
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/lmmi_offset_o
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/lmmi_rdata_i
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/lmmi_rdata_valid_i
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/lmmi_ready_i
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/lmmi_request_o
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/lmmi_resetn_o
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/lmmi_wdata_o
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/lmmi_wr_rdn_o
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/scl_i
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/sda_i
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/scl_oe
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/sda_oe
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/scl_o
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/sda_o
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/sda_spu
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/sda_wpu
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/scl_spu
add wave -noupdate /tb_top/u_i3c_dev/u_i3c_m/lscc_i3c_controller_inst/scl_wpu
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {290299028 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {3678633 ns}
