/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    2025.2.0.48.0
    Soft IP Version: 3.7.0
    2026 02 26 11:50:49
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module I3C_target_inst (scl_io, sda_io, rst_n_i, clk_i, int_o, tgt_rst_o,
    apb_penable_i, apb_psel_i, apb_pwrite_i, apb_paddr_i, apb_pwdata_i,
    apb_pready_o, apb_pslverr_o, apb_prdata_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    inout  scl_io;
    inout  sda_io;
    input  rst_n_i;
    input  clk_i;
    output  int_o;
    output  tgt_rst_o;
    input  apb_penable_i;
    input  apb_psel_i;
    input  apb_pwrite_i;
    input  [31:0]  apb_paddr_i;
    input  [31:0]  apb_pwdata_i;
    output  apb_pready_o;
    output  apb_pslverr_o;
    output  [31:0]  apb_prdata_o;
endmodule