    i3c_s __(.scl_io( ),
        .sda_io( ),
        .rst_n_i( ),
        .clk_i( ),
        .int_o( ),
        .tgt_rst_o( ),
        .apb_penable_i( ),
        .apb_psel_i( ),
        .apb_pwrite_i( ),
        .apb_paddr_i( ),
        .apb_pwdata_i( ),
        .apb_pready_o( ),
        .apb_pslverr_o( ),
        .apb_prdata_o( ));
