// >>>>>>>>>>>>>>>>>>>>>>> COPYRIGHT NOTICE <<<<<<<<<<<<<<<<<<<<<<<<<
// ------------------------------------------------------------------
// Copyright (c) 2019-2025 by Lattice Semiconductor Corporation
// ALL RIGHTS RESERVED
// ------------------------------------------------------------------
//
// IMPORTANT: THIS FILE IS USED BY OR GENERATED BY the LATTICE PROPEL™
// DEVELOPMENT SUITE, WHICH INCLUDES PROPEL BUILDER AND PROPEL SDK.
//
// Lattice grants permission to use this code pursuant to the
// terms of the Lattice Propel License Agreement.
//
// DISCLAIMER:
//
//  LATTICE MAKES NO WARRANTIES ON THIS FILE OR ITS CONTENTS, WHETHER
//  EXPRESSED, IMPLIED, STATUTORY, OR IN ANY PROVISION OF THE LATTICE
//  PROPEL LICENSE AGREEMENT OR COMMUNICATION WITH LICENSEE, AND LATTICE
//  SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTY OF MERCHANTABILITY OR
//  FITNESS FOR A PARTICULAR PURPOSE.  LATTICE DOES NOT WARRANT THAT THE
//  FUNCTIONS CONTAINED HEREIN WILL MEET LICENSEE'S REQUIREMENTS, OR THAT
//  LICENSEE'S OPERATION OF ANY DEVICE, SOFTWARE OR SYSTEM USING THIS FILE
//  OR ITS CONTENTS WILL BE UNINTERRUPTED OR ERROR FREE, OR THAT DEFECTS
//  HEREIN WILL BE CORRECTED.  LICENSEE ASSUMES RESPONSIBILITY FOR
//  SELECTION OF MATERIALS TO ACHIEVE ITS INTENDED RESULTS, AND FOR THE
//  PROPER INSTALLATION, USE, AND RESULTS OBTAINED THEREFROM.  LICENSEE
//  ASSUMES THE ENTIRE RISK OF THE FILE AND ITS CONTENTS PROVING DEFECTIVE
//  OR FAILING TO PERFORM PROPERLY AND IN SUCH EVENT, LICENSEE SHALL
//  ASSUME THE ENTIRE COST AND RISK OF ANY REPAIR, SERVICE, CORRECTION, OR
//  ANY OTHER LIABILITIES OR DAMAGES CAUSED BY OR ASSOCIATED WITH THE
//  SOFTWARE.  IN NO EVENT SHALL LATTICE BE LIABLE TO ANY PARTY FOR DIRECT,
//  INDIRECT,SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST
//  PROFITS, ARISING OUT OF THE USE OF THIS FILE OR ITS CONTENTS, EVEN IF
//  LATTICE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. LATTICE'S
//  SOLE LIABILITY, AND LICENSEE'S SOLE REMEDY, IS SET FORTH ABOVE.
//  LATTICE DOES NOT WARRANT OR REPRESENT THAT THIS FILE, ITS CONTENTS OR
//  USE THEREOF DOES NOT INFRINGE ON THIRD PARTIES' INTELLECTUAL PROPERTY
//  RIGHTS, INCLUDING ANY PATENT. IT IS THE USER'S RESPONSIBILITY TO VERIFY
//  THE USER SOFTWARE DESIGN FOR CONSISTENCY AND FUNCTIONALITY THROUGH THE
//  USE OF FORMAL SOFTWARE VALIDATION METHODS.
// ------------------------------------------------------------------

#include <stdio.h>
#include "terminal.h"

#if (defined TERM_UART_INST_BASE_ADDR) && (!defined LOCAL_UART_GE_V2_7_0)
struct uart_instance term_uart_inst;
#elif (defined TERM_LOCAL_UART_INST_BASE_ADDR) || ((defined TERM_UART_INST_BASE_ADDR) && (defined LOCAL_UART_GE_V2_7_0))
struct local_uart_instance term_uart_inst;
#ifdef TERM_UART_INST_BASE_ADDR
#define UART_BASE_ADDR  TERM_UART_INST_BASE_ADDR
#define UART_BAUD_RATE  TERM_UART_INST_BAUD_RATE
#define UART_SYS_CLK    TERM_UART_INST_SYS_CLK
#define UART_IRQ        TERM_UART_INST_IRQ
#else
#define UART_BASE_ADDR  TERM_LOCAL_UART_INST_BASE_ADDR
#define UART_BAUD_RATE  TERM_LOCAL_UART_INST_BAUD_RATE
#define UART_SYS_CLK    TERM_LOCAL_UART_INST_SYS_CLK
#define UART_IRQ        CPU_INST_0_UART_IRQ
#endif
#endif

static int lscc_uart_putc(char c, FILE *file)
{
#ifdef LSCC_STDIO_UART_APB
		int ret = EOF;
#if (defined TERM_UART_INST_BASE_ADDR) && (!defined LOCAL_UART_GE_V2_7_0)
		ret = uart_putc(&term_uart_inst, c);
		if (c == '\n' && ret == 0)
			ret = uart_putc(&term_uart_inst, '\r');
#elif (defined TERM_LOCAL_UART_INST_BASE_ADDR) || ((defined TERM_UART_INST_BASE_ADDR) && (defined LOCAL_UART_GE_V2_7_0))
		ret = local_uart_putc(&term_uart_inst, c);
		if (c == '\n' && ret == 0)
			ret = local_uart_putc(&term_uart_inst, '\r');
#endif
		return ret;
#else
		return EOF;
#endif
}


static int lscc_uart_getc(FILE *file)
{
#ifdef LSCC_STDIO_UART_APB
	int ret = EOF;
#if ((defined TERM_LOCAL_UART_INST_BASE_ADDR) && (defined LOCAL_UART_GE_V2_7_0)) || ((defined TERM_UART_INST_BASE_ADDR) && (defined LOCAL_UART_GE_V2_7_0))
	unsigned char c;
	ret = local_uart_getc(&term_uart_inst, &c);

	local_uart_putc(&term_uart_inst, c);
	if (c == '\r' && ret == 0)
		local_uart_putc(&term_uart_inst, '\n');

	return c;
#endif
	return ret;
#else
	(void) file;
	return EOF;
#endif
}


static int lscc_uart_flush(FILE *file)
{
#ifdef LSCC_STDIO_UART_APB
	int ret = EOF;
#if ((defined TERM_LOCAL_UART_INST_BASE_ADDR) && (defined LOCAL_UART_GE_V2_7_0)) || ((defined TERM_UART_INST_BASE_ADDR) && (defined LOCAL_UART_GE_V2_7_0))
	ret = local_uart_flush(&term_uart_inst);
#endif
	return ret;
#else
	return EOF;
#endif
}

int terminal_init(unsigned char irq_enable)
{
	int ret = -1;

#if (defined TERM_UART_INST_BASE_ADDR) && (!defined LOCAL_UART_GE_V2_7_0)
#ifndef _UART_NO_INTERRUPTS_
	//setup uart IRQ
	term_uart_inst.intrLevel = TERM_UART_INST_IRQ;
	term_uart_inst.intrAvail = true;
	//pic_isr_register(UART0_INST_IRQ, uart_isr, (void *)&term_uart_inst);
#endif

	//initialize UART
	ret = uart_init(&term_uart_inst, TERM_UART_INST_BASE_ADDR, TERM_UART_INST_SYS_CLK * 1000000, TERM_UART_INST_BAUD_RATE, 1, 8);
#elif (defined TERM_LOCAL_UART_INST_BASE_ADDR) || ((defined TERM_UART_INST_BASE_ADDR) && (defined LOCAL_UART_GE_V2_7_0))

#if UART_IRQ && CPU_INST_0_PLIC_EN
	term_uart_inst.intrLevel = UART_IRQ;
	/*
	 * If local UART connect to IRQ, default enable interrupt mode.
	 * Can set "term_uart_inst.intrAvail = 0" to disable interrupt mode.
	 */
	term_uart_inst.intrAvail = irq_enable;
#endif

	ret = local_uart_init(&term_uart_inst, UART_BASE_ADDR, UART_SYS_CLK * 1000000, UART_BAUD_RATE, 1, 8);

//	local_uart_init(&term_uart_inst, TERM_LOCAL_UART_INST_BASE_ADDR, TERM_LOCAL_UART_INST_SYS_CLK * 1000000, 38400, 1, 8);

#if UART_IRQ && CPU_INST_0_PLIC_EN
	if (term_uart_inst.intrAvail)
	{
		plic_int_register(term_uart_inst.intrLevel, 1, ePRIV_M, local_uart_isr, &term_uart_inst);
		plic_enable(ePRIV_M , term_uart_inst.intrLevel);
	}
#endif

#endif
	iob_init(lscc_uart_putc, lscc_uart_getc, lscc_uart_flush);

	return ret;
}

