/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2025.2.0.2512111315
    Soft IP Version: 3.7.0
    2026 02 02 17:48:11
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module i3c_m (clk_i, rst_n_i, scl_io, sda_io, int_o, apb_penable_i, apb_psel_i,
    apb_pwrite_i, apb_paddr_i, apb_pwdata_i, apb_pready_o, apb_pslverr_o,
    apb_prdata_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  clk_i;
    input  rst_n_i;
    inout  scl_io;
    inout  sda_io;
    output  int_o;
    input  apb_penable_i;
    input  apb_psel_i;
    input  apb_pwrite_i;
    input  [31:0]  apb_paddr_i;
    input  [31:0]  apb_pwdata_i;
    output  apb_pready_o;
    output  apb_pslverr_o;
    output  [31:0]  apb_prdata_o;
endmodule